name: 'Terraform apply'

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 4 * * 1-5" # UTC standard -> KRT = UTC + 9, KRT 13:00 = 04:00 + 9

permissions:
  contents: read

jobs:
  terraform-apply:
    name: 'Terraform apply'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    # Install the latest version of Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    # Configure AWS credentials
    - name: Configure AWS credentials
      run: |-
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile falconlee236
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile falconlee236

    # Create .env file
    - name: Create .env file
      run: echo "WANDB_API_KEY=${{ secrets.WANDB_API_KEY }}" > .env

    # Create terraform.prod.tfvars file
    - name: Create terraform.prod.tfvars file
      run: |-
        cat > terraform.prod.tfvars <<EOF
        dockerhub_id="${{ secrets.DOCKERHUB_id }}"
        dockerhub_pwd ="${{ secrets.DOCKERHUB_pwd }}"
        EOF

    # Create google cloud service account credential.json file
    - name: Configure GCP service account credentials
      id: create-json
      uses: jsdaniell/create-json@1.1.2
      with:
          name: "credentials.json"
          json: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON_VALUE }}

    # Create github ssh key directory
    - name: Configure github ssh
      run: |-
        mkdir .ssh
        echo "${{ secrets.PUBLIC_KEY_GITHUB }}" > .ssh/id_ed25519.pub
        echo "${{ secrets.SECRET_KEY_GITHUB }}" > .ssh/id_ed25519

    # Create GCP instance
    - name: Create GCP Compute Engine
      run: make
